
    

       

      FILEPATH ="./files/test.json"
      FILEPATH1 ="./files/test1.json"	
      XMLTOJSON = "./files/test.xml"
      JSONTOXML = "./files/test2.json"
      FILEPATH4 = "./files/test.txt"

      ["b7a.users"]

      ["b7a.users.admin"]
      password="pass1"
      scopes="scope1,scope2"

      ["b7a.users.user"]
      password="pass2"
      scopes="scope1"  




